on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
    types: [ opened, reopened, synchronize ]
  workflow_call:
  workflow_dispatch:

name: ci-build

env:
  REGISTRY: ghcr.io
  DOTNET_VERSION: 10.0.x

jobs:

  tests:
    name: Tests (${{ matrix.name }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: desktop-repository-server-tunit
            project: DesktopRepositoryServer.Tests/DesktopRepositoryServer.Tests.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '${{ env.DOTNET_VERSION }}'

      - name: Run ${{ matrix.name }} tests
        run: |
          set -euo pipefail
          dotnet test -c Release --proj√©ct ${{ matrix.project }}

  build:
    name: Build (${{ matrix.image }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: docker/DesktopRepositoryServer.Dockerfile
            image: desktop-repository-server

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ${{ matrix.image }}
        uses: ./.github/actions/build-app
        with:
          dockerfile: ${{ matrix.dockerfile }}
          push: ${{ inputs.push || (github.ref_protected && github.event_name != 'pull_request') }}
          image: ${{ matrix.image }}
          platforms: ${{ inputs.platforms || 'linux/amd64' }}
          tag-prefix: ${{ inputs.tag-prefix  || 'rn' }}
          
  promote-image:
    name: Promote Image (${{ matrix.image }})
    needs: [build, tests]
    runs-on: ubuntu-latest
    if: ${{ inputs.push || (github.ref_protected && github.event_name != 'pull_request') }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: desktop-repository-server
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Promote Manifest ${{ matrix.image }}
        uses: ./.github/actions/promote-image
        with:
          image: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.image }}
          run-tag: ${{ inputs.tag-prefix  || 'rn' }}-${{ github.run_number }}-a${{ github.run_attempt }}
          latest: ${{ inputs.latest || false }}
          
  deploy-prod-workflow:
    runs-on: ubuntu-latest
    needs: promote-image
    if: ${{ github.ref_type == 'branch' && github.event_name != 'pull_request' && github.ref_name == 'master' }}
    environment: production
    steps:
      - name: Send repository dispatch
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.GITOPS_PAT }}
          repository: openshock/kubernetes-cluster-gitops
          event-type: update-desktop-repository-server-prod
          client-payload: |
            {
              "tag": "${{ inputs.tag-prefix  || 'rn' }}-${{ github.run_number }}-a${{ github.run_attempt }}"
            }